### ISSUE TITLE
Deployments overview layout breaks in Firefox with long deployment messages

### ISSUE THREAD

**Issue by mrnugget** [applikatoni/applikatoni#10]
The deployments overview layout breaks in Firefox when a deployment has "long" deployment message without the necessary linebreaks.

Screenshot:

![2015-11-10 at 17 25](https://cloud.githubusercontent.com/assets/1185253/11068161/5976eb1e-87d0-11e5-9a3d-c8560b1e58ca.png)

And I, um, have no idea why that is.

To get started on this issue, read through the [Contributing](https://github.com/applikatoni/applikatoni#contributing) section of the README to see how to set up the Applikatoni for development on your machine and how to send a pull request that fixes this issue.

If you have _any_ questions: feel free to ask!

**Comment by Wind0r** [comment]
I think the probleme is that only WebKit supports break-word.
[CSS L33](https://github.com/applikatoni/applikatoni/blob/master/server/assets/applikatoni.css#L33)

The spec only allows: word-break: normal | break-all | keep-all | initial | inherit

break-all will help but mesh up a lot of stuff.
