### ISSUE TITLE
Add SHA and link to "this is what will be deployed"-diff

### ISSUE THREAD

**Issue by mrnugget** [applikatoni/applikatoni#11]
When selecting a target and SHA to deploy Applikatoni will show a diff of the changes to be deployed:

![2015-11-10 at 17 30](https://cloud.githubusercontent.com/assets/1185253/11068301/fc658682-87d0-11e5-98a4-c2f930078ce0.png)

Now, there is a "See diff on GitHub" link, which is quite helpful. But what would be even more awesome would be the SHA of every commit in this diff and a link to the commit on GitHub.

This diff is generated by making a AJAX call and then inserting the diff into the DOM. See the [applikatoni.js file here](https://github.com/applikatoni/applikatoni/blob/cc3fd95074f01aead94440093ee82bb0c3f293a0/server/assets/applikatoni.js#L298-L312). The response from the server is generated in [this handler](https://github.com/applikatoni/applikatoni/blob/cc3fd95074f01aead94440093ee82bb0c3f293a0/server/handlers.go#L149-L190).

The response from the server already contains the SHA of each commit. That means displaying the SHA should only require changes [here in applikatoni.js](https://github.com/applikatoni/applikatoni/blob/cc3fd95074f01aead94440093ee82bb0c3f293a0/server/assets/applikatoni.js#L1-L38) and in the [hogan_templates.tmpl here](https://github.com/applikatoni/applikatoni/blob/cc3fd95074f01aead94440093ee82bb0c3f293a0/server/assets/templates/hogan_templates.tmpl#L151-L171).

Including the URL of the commit requires changes to the GitHub client used by Applikatoni. It should work by adding a `Url` field to the `GitHubCommit` struct [here in github.go](https://github.com/applikatoni/applikatoni/blob/cc3fd95074f01aead94440093ee82bb0c3f293a0/server/github.go#L18-L27). See the [GitHub documentation for the full response](https://developer.github.com/v3/repos/commits/#compare-two-commits).

With the URL being returned by the server the same changes need to be made that displayed the SHA: in `applikatoni.js` and `hogan_templates.tmpl`.

To get started on this issue, read through the [Contributing](https://github.com/applikatoni/applikatoni#contributing) section of the README to see how to set up the Applikatoni for development on your machine and how to send a pull request that fixes this issue.

If you have _any_ questions: feel free to ask!

**Comment by fabrik42** [comment]
We will continue this discussion in the PR: https://github.com/applikatoni/applikatoni/pull/14
