### ISSUE TITLE
Add Slack integration

### ISSUE THREAD

**Issue by mrnugget** [applikatoni/applikatoni#18]
Besides Flowdock it would be awesome to have Applikatoni send messages to [Slack](https://slack.com) (or to either one of them, depending on the configuration).

As I (not a heavy Slack user) understand it, it's possible to create a [Incoming Webhook](https://api.slack.com/incoming-webhooks) for a Slack room. That allows to send a message to the room with a single POST request.

That makes it pretty easy to implement and largely similar to the Flowdock integration. So in order to add Slack integration, I guess it's necessary to do the following:

* Add a `SlackEndpoint` to `Target` exactly like the `FlowdockEndpoint` [here](https://github.com/applikatoni/applikatoni/blob/5d6a06f8cbf76ceb0ea37b09f9209808eb74aac7/models/target.go#L13)
* Create a Slack notifier with a `NotifySlack` and a `newSlackNotifier` function. Exactly like the [Flowdock notifier](https://github.com/applikatoni/applikatoni/blob/5d6a06f8cbf76ceb0ea37b09f9209808eb74aac7/server/flowdock_notifier.go), the [Bugsnag notifier](https://github.com/applikatoni/applikatoni/blob/5d6a06f8cbf76ceb0ea37b09f9209808eb74aac7/server/bugsnag_notifier.go) and the [NewRelic notifier](https://github.com/applikatoni/applikatoni/blob/5d6a06f8cbf76ceb0ea37b09f9209808eb74aac7/server/new_relic_notifier.go)
* Add tests like the ones for the [Bugsnag notifier](https://github.com/applikatoni/applikatoni/blob/5d6a06f8cbf76ceb0ea37b09f9209808eb74aac7/server/bugsnag_notifier_test.go)
* Hook the Slack notifier up in the `main` function: [here is where all notifiers are hooked up](https://github.com/applikatoni/applikatoni/blob/5d6a06f8cbf76ceb0ea37b09f9209808eb74aac7/server/main.go#L127-L132)
* Document the new configuration variable in the README.md file and the `configuration_example.json`.

When this is added we can also add it [to applikatoni.com](https://github.com/applikatoni/applikatoni.github.io).

To get started on this issue, read through the [Contributing](https://github.com/applikatoni/applikatoni#contributing) section of the README to see how to set up the Applikatoni for development on your machine and how to send a pull request that fixes this issue.

If you have _any_ questions or ideas: feel free to ask!

**Comment by Wind0r** [comment]
A little Spoiler ;)

- [x] Code
- [ ] Tests
- [ ] Readme


![bildschirmfoto 2015-12-02 um 23 01 48](https://cloud.githubusercontent.com/assets/2079851/11545660/c3b3769e-9948-11e5-97f2-53fc22ee2654.png)
