### ISSUE TITLE
Generic HTTP Webhooks

### ISSUE THREAD

**Issue by fabrik42** [applikatoni/applikatoni#21]
Hi,

I think it would be a cool idea, if we could support generic HTTP webhooks, like e.g. Travis CI.
This way, you would not need to write your own plugin for simple notifiers.

How I imagine this:
* You can add a list of URLs as webhooks to your config file.
* Every time the state of a deployment changes (start, success fail), the webhooks will be triggered.
* Triggered means: A POST request will be sent to the URLs, with payload containing information about the deploy.
* The payload should be very 	comprehensive, basically including all kind of information that is interesting in the context of the deploy, so we can cover a lot of use cases.

We could add another section in the [configuration file](https://github.com/applikatoni/applikatoni/blob/master/server/configuration_example.json) to provide a list URLs that should be triggered, when the status of a deployment changes. Example:

```
{
  applications: [{
    targets: [{
      webhooks: [
        "https://example.org/notifyme",
        "https://anotherservice.org/notifications"
      ]
    }]
  }]
}
```

The [Travis CI docs](https://docs.travis-ci.com/user/notifications/#Webhook-notification) could be helpful. [Here is an example payload](https://gist.github.com/svenfuchs/1225015).

**Comment by HParker** [comment]
I like this idea. Are you imagining this would take the place of existing notifiers? or maybe the existing notifies could just format the data that is sent along to that url? I think that could really dry up the code.

**Comment by Wind0r** [comment]
Wow. I also thought about that while doing the slack integration.
Also it would enable us to move the other notifiers out of the codebase.
The only Problem then is how we start applikatoni and the other notifiers without having a bloated start script

**Comment by mrnugget** [comment]
I think the way @fabrik42 envisions this is not going to result in removing the Flowdock/Slack/Bugsnag/NewRelic/etc. notifiers, which are quite specific. It's rather a feature that allows users of Applikatoni to receive a generic message from Applikatoni about a deployment state.

**Comment by fabrik42** [comment]
Hi,
I was not thinking about replacing the current notifiers - just adding a more generic one.
The current notifiers are very specific and do some stuff a generic json-via-http-notifier can not do (like special formatting fitted to the individual service).

I have some ideas what I could do with such a generic interface, but I don't want to change much in the architecture before I can see that this idea makes actually sense.

So my proposal would be:
Let's build this in the most simple way und see what we can do with it. If it proves to be useful in the wild, we will learn a lot about new notifiers connected to it and maybe, we can use these insights to enhance the existing built-in notifiers.

What do you think?

Cheers,
Christian

**Comment by HParker** [comment]
Yeah, I agree. Good to have an idea if a http notifier is helpful before assuming existing notifiers share concepts.

**Comment by Wind0r** [comment]
Sounds good :-)
