### ISSUE TITLE
NewRelic notifier sends markdown text that NewRelic can't parse

### ISSUE THREAD

**Issue by mrnugget** [applikatoni/applikatoni#23]
The NewRelic notifier used the same `generateSummary` function the Flowdock notifier uses. [This is the relevant code in the NewRelic notifier](https://github.com/applikatoni/applikatoni/blob/376a190efff67563648fb958874faae2f7a14949/server/new_relic_notifier.go#L52-L62). NewRelic doesn't parse text as Markdown, so this looks really shabby in the NewRelic changelog.

This is a regression that was introduced in #15.

We should use a different function for NewRelic that doesn't use Markdown.

**Comment by mrnugget** [comment]
On second thought I think it would be equally good to either

a) do not send a `deployment[changelog]` to NewRelic at all
b) just send the `Deployment.Comment` as `deployment[changelog]`

**Comment by Wind0r** [comment]
As I suggest in the Slack PR I would like that generateSummary takes a template as argument.
So every notifier can use it.
I will do it in the next days. I also think this is a good way to start the Webhook Notifier.
