### ISSUE TITLE
Get confuse in README and code

### ISSUE THREAD

**Issue by NamPNQ** [applikatoni/applikatoni#27]
In readme i get: ""read_usernames": ["<CAN READ DEPLOYMENT HISTORY BUT NOT DEPLOY>"],"
And https://github.com/applikatoni/applikatoni/blob/master/server/assets/templates/partials.tmpl#L48
That mean, where deploy user can see your app?

**Comment by mrnugget** [comment]
That's exactly right! It's documented [here in the README](https://github.com/applikatoni/applikatoni#application-properties).
