### ISSUE TITLE
Add a super cool startup banner with ASCII art

### ISSUE THREAD

**Issue by mrnugget** [applikatoni/applikatoni#28]
Applikatoni _needs_ a ASCII banner that shows up when Applikatoni is booted. I'm really jealous of [Sidekiq](https://github.com/mperham/sidekiq) and the awesome banner it has:

![2015-12-17 at 09 30](https://cloud.githubusercontent.com/assets/1185253/11864940/de65c0e2-a4a0-11e5-87e1-f12149fb6b40.png)

So! Applikatoni needs this too. I'm thinking about the Applikatoni logo in ASCII, pizza in ASCII, "Applikatoni" in ASCII... 

How to add this?

1. Create a mind-blowing ASCII banner
2. Add the ASCII banner as constant to the `server` package
3. Check if the [environment is development](https://github.com/applikatoni/applikatoni/blob/ab6d94a5f6b4dcb00fddb5cd172e2ce6f68aa235/server/main.go#L35) (we do not want to print this in production, in case someone wants to redirect the output to a logfile)
4. Check if STDOUT is a TTY (again, we do not want to print the banner if STDOUT is redirect to a file, or if it's a pipe)
5. If 3. and 4. are true, the [print the banner here after everything is fully booted up](https://github.com/applikatoni/applikatoni/blob/ab6d94a5f6b4dcb00fddb5cd172e2ce6f68aa235/server/main.go#L166)

To get started on this issue, read through the [Contributing](https://github.com/applikatoni/applikatoni#contributing) section of the README to see how to set up the Applikatoni for development on your machine and how to send a pull request that fixes this issue.

If you have _any_ questions, ideas, comments: feel free to ask!

**Comment by Wind0r** [comment]
Something like this?   

```
                                _ _ _         _              _ 
  //\          __ _ _ __  _ __ | (_) | ____ _| |_ ___  _ __ (_)
 // O \       / _` | '_ \| '_ \| | | |/ / _` | __/ _ \| '_ \| |
|| O o  \    | (_| | |_) | |_) | | |   < (_| | || (_) | | | | |
||__o__O__\   \__,_| .__/| .__/|_|_|_|\_\__,_|\__\___/|_| |_|_|
                  |_|   |_|    
```
Also "Deployments al forno" fit the 80 character limit =)

```
 ___           _                        _             _    __                  
|   \ ___ _ __| |___ _  _ _ __  ___ _ _| |_ ___  __ _| |  / _|___ _ _ _ _  ___ 
| |) / -_) '_ \ / _ \ || | '  \/ -_) ' \  _(_-< / _` | | |  _/ _ \ '_| ' \/ _ \
|___/\___| .__/_\___/\_, |_|_|_\___|_||_\__/__/ \__,_|_| |_| \___/_| |_||_\___/
         |_|         |__/    
```

**Comment by fabrik42** [comment]
This looks pretty cool! We should look for unicode chars that look like mushrooms or pepperonis for the pizza :D

**Comment by Wind0r** [comment]
Someone want to colorize it?
```
                  ___              
                 |  ~~--.                      _ _ _         _              _ 
                 |%=@%%/      __ _ _ __  _ __ | (_) | ____ _| |_ ___  _ __ (_)
                 |o%%%/      / _` | '_ \| '_ \| | | |/ / _` | __/ _ \| '_ \| | 
              __ |%%o/      | (_| | |_) | |_) | | |   < (_| | || (_) | | | | | 
        _,--~~ | |(_/ ._     \__,_| .__/| .__/|_|_|_|\_\__,_|\__\___/|_| |_|_| 
     ,/'  m%%%%| |o/ /  `\.       |_|   |_|    
    /' m%%o(_)%| |/ /o%%m `\       
  /' %%@=%o%%%o|   /(_)o%%% `\         |~\ _  _ | _    _ _  _  _ _|_ _
 /  %o%%%%%=@%%|  /%%o%%@=%%  \        |_/(/_|_)|(_)\/| | |(/_| | | _\
|  (_)%(_)%%o%%| /%%%=@(_)%%%  |             |      /        
| %%o%%%%o%%%(_|/%o%%o%%%%o%%% |              _ |   |` _  _ _  _ 
| %%o%(_)%%%%%o%(_)%%%o%%o%o%% |             (_||  ~|~(_)| | |(_)
|  (_)%%=@%(_)%o%o%%(_)%o(_)%  |         
 \ ~%%o%%%%%o%o%=@%%o%%@%%o%~ /          
  \. ~o%%(_)%%%o%(_)%%(_)o~ ,/       
    \_ ~o%=@%(_)%o%%(_)%~ _/        
      `\_~~o%%%o%%%%%~~_/'        
         `--..____,,--'          
```

**Comment by mrnugget** [comment]
Woah! That's awesome! I'll see if I can give colarizing a go in the next few days!
