### ISSUE TITLE
How to run in dev mode

### ISSUE THREAD

**Issue by NamPNQ** [applikatoni/applikatoni#29]
I try `go run server/main.go` but i get error:
```
# command-line-arguments
server/main.go:42: undefined: Configuration
server/main.go:47: undefined: KillRegistry
server/main.go:70: undefined: readConfiguration
server/main.go:75: undefined: parseTemplates
server/main.go:97: undefined: failUnfinishedDeployments
server/main.go:110: undefined: NewKillRegistry
server/main.go:113: undefined: SendDailyDigests
server/main.go:126: undefined: newLogEntrySaver
server/main.go:128: undefined: newBugsnagNotifier
server/main.go:130: undefined: newFlowdockNotifier
server/main.go:130: too many errors

```
Sorry, I'm go newbie

**Comment by mrnugget** [comment]
To run the server locally you need to run `cd server && go build -o applikatoni . && ./applikatoni`, aftering installing all the dependencies with `go get ./...`.

For more information read through the [Contributing](https://github.com/applikatoni/applikatoni#contributing) section in the README and maybe read through the [Getting Started](https://golang.org/doc/install) and [How to Write Go Code](https://golang.org/doc/code.html) guides provided by the Go team.

And for what it's worth, here are the notes a colleague and I wrote down while setting up a local dev environment for Applikatoni on his machine:

```
Install Go:

  brew update
  brew install go
  brew install sqlite3

Setup Go:
  https://golang.org/doc/install

  export GOPATH=$HOME/work
  export PATH="$GOPATH/bin:$PATH"

  follow "test your installation" steps

Setup Applikatoni:

  mkdir -p $GOPATH/src/github.com/applikatoni
  cd $GOPATH/src/github.com/applikatoni
  git clone https://github.com/applikatoni/applikatoni.git

Install applikatoni dependencies:

  go get -v ./…
  go get bitbucket.org/liamstask/goose/cmd/goose
  cd server && vim db/dbconf.yml (if you want to change config)
  cd server && goose -env="development" up
  cd server && goose -env="test" up

Run tests, to see if you’re lucky:

  go test -v ./...

Create developer applikation on github:

  https://github.com/settings/applications/

  Set up local page and url for authorization callback URL (http://localhost:8080)

Edit the configuration.json

Run applikatoni

  cd server && go build . -o applikatoni && ./applikatoni
```

**Comment by mrnugget** [comment]
Also, check out the [Vagrantfile](https://github.com/applikatoni/applikatoni/blob/5717059f901a7118ffcf83c63a85b8567ab059b6/Vagrantfile) to see how to setup the whole toolchain on a Linux system (most of it translates well to a OS X system).

**Comment by NamPNQ** [comment]
Thanks you, It's very helpful
