### ISSUE TITLE
Error after revoking access in GitHub and reauthenticating

### ISSUE THREAD

**Issue by nlochschmidt** [applikatoni/applikatoni#40]
Currently Applikatoni does not save the new access token after a previous access token has been revoked through the GitHub settings at https://github.com/settings/applications.

As a result the login still works, however the pull requests and branches can not be fetched through the GitHub API.

**Comment by mrnugget** [comment]
Thanks for reporting this! I can confirm how and why this is happening. When a user authorizes Applikatoni to access their GitHub account as part of the OAuth2 auth process, the user is redirected to the OAuth2 callback handler:

https://github.com/applikatoni/applikatoni/blob/c2783d695dcba40e6572953b3580b0b46aed9548/server/handlers.go#L441

The interesting part is here:

https://github.com/applikatoni/applikatoni/blob/c2783d695dcba40e6572953b3580b0b46aed9548/server/handlers.go#L461-L475

We instantiate a GitHub client with the newly received access token (which is recreated everytime the user re-authorizes GitHub) and then update the in-memory model of the User with the new  GitHub information. So far, so good. Now we have a GitHub user at our hands. It's time to either turn that into an Applikatoni user or get an existing Applikatoni user with that GitHub ID from our database:

https://github.com/applikatoni/applikatoni/blob/c2783d695dcba40e6572953b3580b0b46aed9548/server/handlers.go#L470-L475

Now, when we received a _new_ access token that matches an _existing_ user in our database, this is the point where this piece of information gets lost. We simply do a `getOrCreate` here: 1) create the user with the GitHub data we just received or 2) fetch the user with this ID from the database. And 2) is wrong.

Here's a rough plan of what needs to be done:
1. Extend [this test](https://github.com/applikatoni/applikatoni/blob/c2783d695dcba40e6572953b3580b0b46aed9548/server/database_test.go#L520-L538) so it modifies the `user` (new username or accesstoken for example) and passes it to `getOrCreateUser`. Then assert that after this call the user still has the modified username and also assert with a plain SQL query that the new user information has been persisted.
2. Make the test pass by modifying the function to check if the user exists and if it does, it updates the user (I think we can safely be ignorant about `UPDATE`s that wouldn't modify anything). If the user does not exist, it creates the user. Just like before.
3. Rename the function: `getOrCreate` is then misleading. I think `updateOrCreate` is then the better name.

Do you want to take a stab at this? I'd happily merge a proper PR :)

If not: I don't know when I'll find the time to actually fix this properly as I'm currently invested in a lot of other side projects with a higher priority for me than Applikatoni.

**Comment by nlochschmidt** [comment]
Thanks for the detailed analysis and sketch of a solution. Since I don't have much experience in developing Go, I might as well use this opportunity to try it out 👍
