### ISSUE TITLE
[Question] Local use? 

### ISSUE THREAD

**Issue by 0x5c** [applikatoni/applikatoni#42]
Can Applikatoni work on the same host as the deployment target server? ie: without ssh

**Comment by mrnugget** [comment]
(Sorry for the late reply -- holidays and all)

There is no built-in functionality that ensures that Applikatoni works without SSH. In fact, Applikatoni is built with SSH in mind. So the only possible current solution is to have Applikatoni connect to localhost, if that's possible (haven't tried it yet!)
